import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HomeHeader from "@/components/home/HomeHeader";
import HomeMain from "@/components/home/HomeMain";
import MainLoading from "@/components/Loading.js/MainLoading";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setLoading(!loading);
  }, []);

  return (
    <>
      <MainLoading loading={loading} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader />
      <HomeMain />
    </>
  );
}
